### ISSUE TITLE
Conda enviroment not working due to elasticsearch dependency

### ISSUE THREAD

**Issue by aecio** [VIDA-NYU/domain_discovery_tool_deprecated#43]
Latest elasticsearch conda package (1.7) doesn't include executable file to start elasticsearch, or the name changed. ElasticSearch doesn't start when running supervisor:

```
$ supervisord
2015-10-15 14:24:27,667 INFO RPC interface 'supervisor' initialized
2015-10-15 14:24:27,668 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2015-10-15 14:24:27,668 INFO supervisord started with pid 16981
2015-10-15 14:24:28,669 INFO spawnerr: can't find command 'elasticsearch'
2015-10-15 14:24:28,671 INFO spawned: 'ddt' with pid 16985
2015-10-15 14:24:29,703 INFO spawnerr: can't find command 'elasticsearch'
2015-10-15 14:24:29,704 INFO success: ddt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-10-15 14:24:31,706 INFO spawnerr: can't find command 'elasticsearch'
2015-10-15 14:24:34,710 INFO spawnerr: can't find command 'elasticsearch'
2015-10-15 14:24:34,710 INFO gave up: elasticsearch entered FATAL state, too many start retries too quickly
```

Specifying a elasticsearch version <= 1.6 in the `environment.yml` file fixes this problem, but another problem happens when starting DDT services through supervisor:

```
$ supervisord
2015-10-15 14:28:14,162 INFO RPC interface 'supervisor' initialized
2015-10-15 14:28:14,162 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2015-10-15 14:28:14,162 INFO supervisord started with pid 17341
2015-10-15 14:28:15,165 INFO spawned: 'elasticsearch' with pid 17344
2015-10-15 14:28:15,168 INFO spawned: 'ddt' with pid 17345
2015-10-15 14:28:15,600 INFO exited: ddt (exit status 1; not expected)
2015-10-15 14:28:16,725 INFO success: elasticsearch entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-10-15 14:28:16,726 INFO spawned: 'ddt' with pid 17450
2015-10-15 14:28:17,196 INFO exited: ddt (exit status 1; not expected)
2015-10-15 14:28:19,239 INFO spawned: 'ddt' with pid 17627
2015-10-15 14:28:19,623 INFO exited: ddt (exit status 1; not expected)
2015-10-15 14:28:23,187 INFO spawned: 'ddt' with pid 17736
2015-10-15 14:28:23,590 INFO exited: ddt (exit status 1; not expected)
2015-10-15 14:28:24,591 INFO gave up: ddt entered FATAL state, too many start retries too quickly
```

and in the file `./logs/ddt-stderr---supervisor-YpGRaX.log`:

```
Traceback (most recent call last):
  File "/home/aeciosantos/workspace/domain_discovery_tool/vis/server.py", line 5, in <module>
    from crawler_model_adapter import *
  File "/home/aeciosantos/workspace/domain_discovery_tool/vis/crawler_model_adapter.py", line 2, in <module>
    from models.crawlermodel import *
  File "/home/aeciosantos/workspace/domain_discovery_tool/models/crawlermodel.py", line 22, in <module>
    from elasticsearch import Elasticsearch
ImportError: No module named elasticsearch
```

@ahmadia @brittainhard Do you guys know if this a problem of elasticsearch packages or in DDT's conda env?

Thanks @felipemoraes for reporting the problem.

**Comment by ahmadia** [comment]
Hmnn, I'm not sure about the former (maybe you're acquiring elasticsearch from a different channel than we intend?) but the latter seems to be a missing `elasticsearch` under pip?

**Comment by britthard** [comment]
I think what's going on here is that there are two packages, both of which are called elasticsearch. One is the service and the other is the wrapper around it. To fix this, we simply installed elasticsearch from pip instead of from conda. It looks like this:

```
name: memex
channels:
    - memex
dependencies:
    - elasticsearch=1.6.0
    - pip
    - pip:
        - elasticsearch
```

(cut a bunch of dependencies out to make it clearer).

**Comment by britthard** [comment]
It's worth talking about, whether we should change the name of the elasticsearch service package to elasticsearch-service to avoid this problem. Elastic has you install their package through pip just as "elasticsearch" and not "elasticsearch-py" for some reason. https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/index.html

**Comment by ahmadia** [comment]
> Elastic has you install their package through pip just as "elasticsearch" and not "elasticsearch-py" for some reason.

That's pretty standard for installing from a Python-specific repository.

I'd be +1 on changing elasticsearch to elasticsearch-server, but we probably need to discuss a little more before doing so unless we're "broken" in production.

**Comment by aecio** [comment]
I thinks renaming elasticsearch to elasticsearch-server makes sense too.

I tried the solution that @brittainhard suggested but it didn't work for me.

About elasticsearch 1.7, I think I'm getting the package from memex channel, since it's the only channel declared in [`enviroment.yml`](https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/environment.yml) file. And the downloaded package doesn't include the binary files:

```
$ tree ~/.anaconda/pkgs/elasticsearch-1.7.0-py27_0
~/.anaconda/pkgs/elasticsearch-1.7.0-py27_0
├── info
│   ├── files
│   ├── git
│   ├── index.json
│   ├── recipe
│   │   ├── bld.bat
│   │   ├── build.sh
│   │   └── meta.yaml
│   └── recipe.json
└── lib
    └── python2.7
        └── site-packages
            ├── elasticsearch-1.7.0-py2.7.egg
            └── elasticsearch.pth

5 directories, 9 files
```

Whereas if I run the same command in the package 1.6, it does include the executable and jar files:

```
$ tree ~/.anaconda/pkgs/elasticsearch-1.6.0-0/
~/.anaconda/pkgs/elasticsearch-1.6.0-0/
├── bin
│   └── elasticsearch -> ../lib/elasticsearch/bin/elasticsearch
├── info
│   ├── files
│   ├── git
│   ├── index.json
│   ├── recipe
│   │   ├── bld.bat
│   │   ├── build.sh
│   │   ├── elasticsearch.yml
│   │   └── meta.yaml
│   └── recipe.json
└── lib
    └── elasticsearch
        ├── bin
        │   ├── elasticsearch
        │   ├── elasticsearch.bat
        │   ├── elasticsearch.in.bat
        │   ├── elasticsearch.in.sh
        │   ├── plugin
        │   ├── plugin.bat
        │   └── service.bat
        ├── config
        │   ├── elasticsearch.yml
        │   └── logging.yml
        └── lib
            ├── [a lot of jar files...]

8 directories, 58 files
```

It looks like the `elasticsearch` =1.7.0 package is not elasticsearch server anymore, but the same as the `elasticsearch-py` package:

```
$ tree ~/.anaconda/pkgs/elasticsearch-py-1.6.0-py27_0
~/.anaconda/pkgs/elasticsearch-py-1.6.0-py27_0
├── info
│   ├── files
│   ├── index.json
│   ├── recipe
│   │   ├── bld.bat
│   │   ├── build.sh
│   │   └── meta.yaml
│   └── recipe.json
└── lib
    └── python2.7
        └── site-packages
            ├── elasticsearch-1.6.0-py2.7.egg
            └── elasticsearch.pth

5 directories, 8 files
```

**Comment by ahmadia** [comment]
@aecio - I see the problem and I can fix it.  I'll try to have something to you by Monday.

**Comment by aecio** [comment]
Thanks @ahmadia.

**Comment by aecio** [comment]
Hi guys,

I'm testing this once more today, and I found that this second problem (ImportError) is a side effect of the first problem. If change the package `elasticsearch` to `elasticsearch=1.6.0`, and then run `conda env update`, the first problem is solved but I still get the ImportError. But if I deactivate the env, an then remove the env with `conda env remove -n ddt`, then `conda env update`, and finally `source activate`, the import error is solved. So it looks that there's some kind of "cache" in conda that makes the problem happen.

**Comment by ahmadia** [comment]
Sorry @aecio this slipped by me yesterday.

**Comment by ahmadia** [comment]
Looking at this now.

**Comment by aecio** [comment]
That's ok. For now, I think the fix for this in DDT is just to force `elasticsearch` version 1.6.0. But there may be a more general bug in conda or in the binstar packages.

**Comment by ahmadia** [comment]
There's an elasticsearch 1.7 in the memex channel that I probably accidentally uploaded.  I'm inspecting it now.

**Comment by ahmadia** [comment]
Okay, there was a miscommunication within our team and that Python package got accidentally uploaded last week.  Sorry for the trouble @aecio, everything should be fixed now with a `conda update`.

**Comment by aecio** [comment]
Thanks for the help. I'm closing this issue now.
