### ISSUE TITLE
OutOfMemoryError on statistics page

### ISSUE THREAD

**Issue by aecio** [VIDA-NYU/domain_discovery_tool_deprecated#69]
Page statistics show the following error when there is a big number of pages indexed.

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/aeciosantos/.anaconda2/envs/ddt/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/aeciosantos/.anaconda2/envs/ddt/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/aeciosantos/.anaconda2/envs/ddt/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/aeciosantos/workspace/ddt/vis/server.py", line 357, in statistics
    pages_dates = self._crawler.getPagesDates(session)
  File "/home/aeciosantos/workspace/ddt/vis/crawler_model_adapter.py", line 194, in getPagesDates
    return self._crawlerModel.getPagesDates(session)
  File "/home/aeciosantos/workspace/ddt/models/crawlermodel.py", line 1042, in getPagesDates
    return get_pages_datetimes(es_info["activeCrawlerIndex"])
  File "/home/aeciosantos/workspace/ddt/elastic/get_documents.py", line 193, in get_pages_datetimes
    items = es.search(index_name, size=100000)["hits"]["hits"]
  File "/home/aeciosantos/.anaconda2/envs/ddt/lib/python2.7/site-packages/elasticsearch-1.6.0-py2.7.egg/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/aeciosantos/.anaconda2/envs/ddt/lib/python2.7/site-packages/elasticsearch-1.6.0-py2.7.egg/elasticsearch/client/__init__.py", line 506, in search
    params=params, body=body)
  File "/home/aeciosantos/.anaconda2/envs/ddt/lib/python2.7/site-packages/elasticsearch-1.6.0-py2.7.egg/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/aeciosantos/.anaconda2/envs/ddt/lib/python2.7/site-packages/elasticsearch-1.6.0-py2.7.egg/elasticsearch/connection/http_urllib3.py", line 89, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/aeciosantos/.anaconda2/envs/ddt/lib/python2.7/site-packages/elasticsearch-1.6.0-py2.7.egg/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
TransportError: TransportError(500, u'OutOfMemoryError[Java heap space]')
```

**Comment by yamsgithub** [comment]
Did you try increasing the heap size of your elasticsearch?

**Comment by yamsgithub** [comment]
Increasing the heap size of elasticsearch does solve the problem. But I am leaving this issue open so @brittainhard can check if there is a better way to handle the data with smaller memory footprint.
