### ISSUE TITLE
First request fails because domainId is not set yet

### ISSUE THREAD

**Issue by aecio** [VIDA-NYU/domain_discovery_tool_deprecated#87]
This same error happens to both `/getAvailableQueries` and `/getAvailableTags`:

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "~/.anaconda2/envs/ddt/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "~/.anaconda2/envs/ddt/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "~/.anaconda2/envs/ddt/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "~/workspace/ddt/vis/server.py", line 159, in getAvailableQueries
    res = self._crawler.getAvailableQueries(session)
  File "~/workspace/ddt/vis/crawler_model_adapter.py", line 173, in getAvailableQueries
    return self._crawlerModel.getAvailableQueries(session)
  File "~/workspace/ddt/models/crawlermodel.py", line 128, in getAvailableQueries
    es_info = self.esInfo(session['domainId'])
KeyError: 'domainId'
```

**Comment by yamsgithub** [comment]
Should be fixed with the latest update
